name: Discord Auto Status

on:
  push:
  schedule:
    - cron: '0 */8 * * *'  # every 8 hours

jobs:
  send-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read status file
        id: get_status
        run: |
          content=$(cat status.txt)
          echo "STATUS=$content" >> $GITHUB_ENV

      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ${{ env.STATUS }}
