name: Discord Ping

on:
  push:
    branches:
      - main

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "✅ GitHub push detected on main branch"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
